# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Main_UI.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(946, 691)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
#        self.label_logo = QtWidgets.QLabel(self.centralwidget)
#        self.label_logo.setObjectName("label_logo")
#        self.gridLayout_2.addWidget(self.label_logo, 0, 0, 1, 1)
        
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_logo = QtWidgets.QLabel(self.centralwidget)
        self.label_logo.setObjectName("label_logo")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.label_number = QtWidgets.QLabel(self.centralwidget)
        self.label_number.setObjectName("label_number")
        self.horizontalLayout_4.addWidget(self.label_number)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.label_time = QtWidgets.QLabel(self.centralwidget)
        self.label_time.setObjectName("label_time")
        self.label_time.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_time.setStyleSheet('border-width: 1px;border-style: solid;border-color: rgb(0, 0, 139);')
        self.horizontalLayout_4.addWidget(self.label_time)       
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.gridLayout_2.addLayout(self.horizontalLayout_4, 0, 1, 1, 1)
        
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.Btn_setting = QtWidgets.QPushButton(self.centralwidget)
        self.Btn_setting.setObjectName("Btn_setting")
        self.horizontalLayout_3.addWidget(self.Btn_setting)
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_3.addWidget(self.pushButton_2)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 0, 2, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        
        
        self.label_Cam1 = QtWidgets.QLabel(self.centralwidget)
        self.label_Cam1.setMinimumSize(QtCore.QSize(300, 250))
        self.label_Cam1.setObjectName("label_Cam1")
        self.horizontalLayout.addWidget(self.label_Cam1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.label_Shoot1 = QtWidgets.QLabel(self.centralwidget)
        self.label_Shoot1.setMinimumSize(QtCore.QSize(300, 250))
        self.label_Shoot1.setObjectName("label_Shoot1")
        self.horizontalLayout.addWidget(self.label_Shoot1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.label_chart1 = QtWidgets.QLabel(self.centralwidget)
        self.label_chart1.setMinimumSize(QtCore.QSize(300, 250))
        self.label_chart1.setObjectName("label_chart1")
        self.horizontalLayout.addWidget(self.label_chart1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem5)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_Cam2 = QtWidgets.QLabel(self.centralwidget)
        self.label_Cam2.setMinimumSize(QtCore.QSize(300, 250))
        self.label_Cam2.setObjectName("label_Cam2")
        self.horizontalLayout_2.addWidget(self.label_Cam2)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem6)
        self.label_Shoot2 = QtWidgets.QLabel(self.centralwidget)
        self.label_Shoot2.setMinimumSize(QtCore.QSize(300, 250))
        self.label_Shoot2.setObjectName("label_Shoot2")
        self.horizontalLayout_2.addWidget(self.label_Shoot2)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem7)
        self.label_chart2 = QtWidgets.QLabel(self.centralwidget)
        self.label_chart2.setMinimumSize(QtCore.QSize(300, 250))
        self.label_chart2.setObjectName("label_chart2")
        self.horizontalLayout_2.addWidget(self.label_chart2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem8)
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout.addWidget(self.textBrowser)
        self.gridLayout_2.addLayout(self.verticalLayout, 1, 0, 1, 3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 946, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_logo.setText(_translate("MainWindow", "TextLabel"))
        self.label_number.setText(_translate("MainWindow", "EquipmentNo"))
        self.label_time.setText(_translate("MainWindow", "TextLabel"))
        self.Btn_setting.setText(_translate("MainWindow", "Setting"))
        self.pushButton_2.setText(_translate("MainWindow", "Log in/out"))
        self.label_Cam1.setText(_translate("MainWindow", "TextLabel"))
        self.label_Shoot1.setText(_translate("MainWindow", "TextLabel"))
        self.label_chart1.setText(_translate("MainWindow", "TextLabel"))
        self.label_Cam2.setText(_translate("MainWindow", "TextLabel"))
        self.label_Shoot2.setText(_translate("MainWindow", "TextLabel"))
        self.label_chart2.setText(_translate("MainWindow", "TextLabel"))
